mosquitto:
  image: eclipse-mosquitto
  container_name: mosquitto
  volumes:
    - /opt/mosquitto/config:/mosquitto/config/
    - /opt/mosquitto/data:/mosquitto/data
    - /opt/mosquitto/log:/mosquitto/log
  ports:
    - 1883:1883
    - 9001:9001
